DROP TABLE quiz_users PURGE;

CREATE TABLE quiz_users (
                            email_id         VARCHAR2(50) PRIMARY KEY,
                            password         VARCHAR2(500) NOT NULL,
                            username         VARCHAR2(20) NOT NULL UNIQUE,
                            phone_number     VARCHAR2(20) NOT NULL,
                            gender           VARCHAR2(10),
                            date_of_birth    DATE,
                            last_logged_in   DATE,
                            image_url        VARCHAR2(50),
                            image            BFILE,
                            pro_version      CHAR(1),
                            salt VARCHAR2(500)
);

INSERT INTO quiz_users VALUES (
                                  'ankur.patel@humber.ca',
                                  'Ankur@123',
                                  'Dark_Knight',
                                  '+1-612-7788',
                                  'Male',
                                  '20-Dec-1994',
                                  '19-Jan-2019',
                                  'abc',
                                  bfilename('GIF_FILES', 'Ankur.JPG'),
                                  'Y',
                                  ''
                              );


SELECT
    *
FROM
    quiz_users;

COMMIT;

DROP TABLE quiz_category;

CREATE TABLE quiz_category (
    category_no        NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
    PRIMARY KEY,
    category_name      VARCHAR2(20),
    category_details   VARCHAR2(20)
);

DROP TABLE quiz_questions PURGE;

CREATE TABLE quiz_questions (
    question_no   NUMBER(2),
    question      VARCHAR2(255),
    option1       VARCHAR2(255),
    option2       VARCHAR2(255),
    option3       VARCHAR2(255),
    option4       VARCHAR2(255),
    correct_ans   NUMBER(2),
    points        NUMBER,
    category_no   NUMBER NOT NULL
        REFERENCES quiz_category ( category_no )
);

DROP TABLE quiz_result PURGE;

CREATE TABLE quiz_result (
    quiz_no            NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
    PRIMARY KEY,
    score_obtained     NUMBER,
    percentage_score   NUMBER,
    time_used          NUMBER,
    username           VARCHAR2(20) NOT NULL
        REFERENCES quiz_users ( username )
);

commit;