DROP TABLE quiz_users PURGE;

CREATE TABLE quiz_users (
    email_id         VARCHAR2(50) PRIMARY KEY,
    password         VARCHAR2(500) NOT NULL,
    username         VARCHAR2(20) NOT NULL UNIQUE,
    phone_number     VARCHAR2(20) NOT NULL,
    gender           VARCHAR2(25),
    date_of_birth    DATE,
    last_logged_in   DATE,
    image_url        VARCHAR2(50),
    image            BLOB,
    pro_version      CHAR(1),
    salt VARCHAR2(500)
);

INSERT INTO quiz_users VALUES (
                                  'ankur.patel@humber.ca',
                                  'Ankur@123',
                                  'Dark_Knight',
                                  '+1-612-7788',
                                  'Male',
                                  '20-Dec-1994',
                                  '19-Jan-2019',
                                  'abc',
                                  bfilename('GIF_FILES', 'Ankur.JPG'),
                                  'Y',
                                  ''
                              );

SELECT
    *
FROM
    quiz_users;

    alter table quiz_users modify last_logged_in timestamp;

COMMIT;

DROP TABLE quiz_category;

CREATE TABLE quiz_category (
    category_no     NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
    PRIMARY KEY,
    category_name   VARCHAR2(20)
);

CREATE TABLE quiz_questions (
    question_no   NUMBER(2),
    question      VARCHAR2(255),
    option1       VARCHAR2(255),
    option2       VARCHAR2(255),
    option3       VARCHAR2(255),
    option4       VARCHAR2(255),
    correct_ans   NUMBER(2),
    points        NUMBER,
    category_no   NUMBER NOT NULL
        REFERENCES quiz_category ( category_no )
);

CREATE TABLE quiz_result (
    quiz_no            NUMBER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1
    PRIMARY KEY,
    score_obtained     NUMBER,
    percentage_score   NUMBER,
    time_used          NUMBER,
    username           VARCHAR2(20) NOT NULL
        REFERENCES quiz_users ( username )
);

INSERT INTO quiz_category ( category_name ) VALUES ( 'Java' );

INSERT INTO quiz_category ( category_name ) VALUES ( 'Oracle' );

INSERT INTO quiz_category ( category_name ) VALUES ( 'TV Show' );

INSERT INTO quiz_category ( category_name ) VALUES ( 'Movies' );

INSERT INTO quiz_category ( category_name ) VALUES ( 'Fun' );

SELECT
    *
FROM
    quiz_category;

COMMIT;

insert into quiz_questions values(1, 'The Plaka is the oldest quarter of which city?', 'Athens','Prague','Rome','Vienna',1,3,5);
insert into quiz_questions values(2, 'Apart from Mad George, which kinder nickname did George III have?','Big George','Farmer Giles','Farmer George','Happy George',3,3,5);
insert into quiz_questions values(3, 'The House of Lancaster kings were all called what?','Charles','Edward','George','Henry',4,3,5);
insert into quiz_questions values(4, 'Who was the last viceroy of India?','Clive','George VI','Prince Louis of Battenburg','Lord Louis Mountbatten',4,3,5);
insert into quiz_questions values(5, 'Who was the lead actor in the film ''12 Angry Men''?', 'Cary Grant','Marlon Brando','Henry Fonda','Jimmy Stewart',3,3,5);
insert into quiz_questions values(6, 'What is the longest river in France?', 'Loire','Seine','Rhone','Gironde',1,3,5);
insert into quiz_questions values(7, 'Who become the first batsman to smash 500 or more sixes in international cricket?', 'David Warner','Kane Williamson','Virat Kohli','Chris Gayle',4,3,5);
insert into quiz_questions values(8, 'Which country topped in the ISSF World Cup 2019?', 'Singapore','India','Brazil','Spain',2,3,5);
insert into quiz_questions values(9, 'The Opium war id held between which two countries?', 'England and France','China and Russia','Russia and England','China and England',4,3,5);
insert into quiz_questions values(10, 'The oldest dynasty still ruling in which country?', 'India','Iran','Japan','England',3,3,5);